name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

  docker_build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/jouvemanager:latest -f src/JouveManager.WebApi/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/jouvemanager:latest

  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
    - uses: actions/checkout@v4
    
    - uses: superfly/flyctl-actions/setup-flyctl@master

    - run: flyctl deploy --remote-only --image ${{ secrets.DOCKER_USERNAME }}/jouvemanager:latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
